#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Dec 17 17:04:03 BRT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Voyager shader 2.0.8.zip
enableShaders=false
